import type { AnalyticsDrawdown, AnalyticsEdge, AnalyticsExecution, AnalyticsPerformance, MonteCarloSimulation, RrSimulation, StopLossSimulation } from '../../api/analytics'

const identity = { id: 'source-1', type: 'session' as const, title: 'Verified journal', subtitle: 'Live test source', status: 'completed' }
export const performanceFixture: AnalyticsPerformance = {
  source: { ...identity, initialBalance: 100_000 },
  overview: { totalPnl: 1_250, pnlPercent: 1.25, accountBalance: 101_250, winRate: 50, totalTrades: 2, longTrades: 1, shortTrades: 1, breakevenTrades: 0 },
  equityCurve: [{ tradeIndex: 0, tradeId: null, closedAt: null, cumulativePnl: 0, balance: 100_000 }, { tradeIndex: 1, tradeId: 't1', closedAt: '2025-03-01T12:00:00Z', cumulativePnl: 1_250, balance: 101_250 }],
  riskReward: { averageRr: 1.2, maxRr: 2, idealAverageRr: 2.4, maxIdealRr: 3, couldHaveProfitOrBreakeven: 0, couldHaveMaxIdealRr: 0, series: { actual: [{ tradeIndex: 1, tradeId: 't1', closedAt: '2025-03-01T12:00:00Z', rr: 2 }], ideal: [], missed: [] }, excludedTrades: 0, missingMarketDataTrades: 0 },
  expectancy: { value: 625, averageWin: 1_500, averageLoss: -250, profitFactor: 6 },
  winners: { total: 1, bestWinPercent: 1.5, averageWinPercent: 1.5, averageDurationSeconds: 3600, maxConsecutive: 1, averageConsecutive: 1 },
  losers: { total: 1, worstLossPercent: -0.25, averageLossPercent: -0.25, averageDurationSeconds: 1800, maxConsecutive: 1, averageConsecutive: 1 },
  bySide: { buy: { trades: 1, tradePercent: 50, wins: 1, winRate: 100 }, sell: { trades: 1, tradePercent: 50, wins: 0, winRate: 0 } },
  bySession: [{ session: 'New York', totalTrades: 2, winRate: 50, averageRr: 1.2, totalPnl: 1_250 }],
  byTime: { pnl: [{ hour: 12, profit: 1_500, loss: -250, netPnl: 1_250, averageRr: 1.2, profitPercent: 1.25, winRate: 50, totalTrades: 2 }], rr: [{ hour: 12, profit: 1_500, loss: -250, netPnl: 1_250, averageRr: 1.2, profitPercent: 1.25, winRate: 50, totalTrades: 2 }], profitPercent: [{ hour: 12, profit: 1_500, loss: -250, netPnl: 1_250, averageRr: 1.2, profitPercent: 1.25, winRate: 50, totalTrades: 2 }], winRate: [{ hour: 12, profit: 1_500, loss: -250, netPnl: 1_250, averageRr: 1.2, profitPercent: 1.25, winRate: 50, totalTrades: 2 }] },
  byDay: [{ day: 'Saturday', profit: 1_500, loss: -250, netPnl: 1_250, totalTrades: 2, wins: 1, winRate: 50 }],
  byMonth: [{ month: '2025-03', monthlyPnl: 1_250, monthlyGainPercent: 1.25, endingBalance: 101_250, totalTrades: 2 }],
  calendar: [{ date: '2025-03-01', trades: 2, wins: 1, losses: 1, breakeven: 0, pnl: 1_250, pnlPercent: 1.25, endingBalance: 101_250 }],
  frequency: { byWeekday: [{ day: 'Saturday', averageTrades: 2 }], byWeek: [{ weekStart: '2025-02-24', weekEnd: '2025-03-02', totalTrades: 2 }], byMonth: [{ month: '2025-03', totalTrades: 2 }], averageTradesPerDay: 2, averageTradesPerWeek: 2, averageTradesPerMonth: 2 },
}

export const drawdownFixture: AnalyticsDrawdown = { source: performanceFixture.source, equityDrawdown: { points: [{ tradeIndex: 1, tradeId: 't1', closedAt: '2025-03-01T12:00:00Z', equity: 99_750, peakEquity: 100_000, drawdownAmount: -250, drawdownPercent: -0.25 }], maxDrawdownAmount: -250, maxDrawdownPercent: -0.25, averageDrawdownAmount: -250, averageDrawdownPercent: -0.25, averageRecoveryDays: 1, drawdownFrequency: 1, completedEpisodes: 1, openEpisode: false }, maximumAdverseExcursion: { unit: 'R', histogram: [{ fromInclusive: 0, toExclusive: 0.5, label: '0–0.5', count: 1 }], winningTrades: { averageMaeR: .2, minMaeR: .2, maxMaeR: .2, includedTrades: 1, excludedNoInitialRisk: 0, missingMarketDataTrades: 0 } } }

export const edgeFixture: AnalyticsEdge = { source: { id: identity.id, type: identity.type, title: identity.title, tradeCount: 80 }, calculationVersion: 'v1', audit: { totalTrades: 80, eligibleRTrades: 80, excludedNoRMultiple: 0, eligibleExcursionTrades: 80, excludedNoInitialRisk: 0, marketDataCoverageTrades: 80 }, edge: { sampleSize: 80, expectancyR: .2, winRate: 52, averageWinR: 1.5, averageLossR: -1, averageRR: 1.5, breakevenRate: 40, tStatistic: 2.2, pValue: .03, verdict: 'edge' }, bootstrap: { expectancyR: { lower: .05, median: .2, upper: .36 }, maxDrawdownR: { lower: -8, median: -5, upper: -3 }, sharpe: { lower: .2, median: .5, upper: .8 }, iterations: 1_000, confidence: .9, seed: 42 }, decomposition: { payoffAsymmetry: 1.5, averageMfeR: 2, averageMaeR: .5, averageRealizedR: .2, captureRatio: .6, timingFlag: 'balanced', topN: 5, topNConcentrationPercent: 30, concentrationFlag: 'diversified' }, walkForward: { split: .8, inSample: { trades: 64, expectancyR: .22 }, outOfSample: { trades: 16, expectancyR: .15 }, expectancyDeltaR: -.07, retentionRatio: .68, windows: [{ label: 'W1', startTs: null, endTs: null, trades: 16, expectancyR: .15 }], parameterSensitivity: null }, sizing: { method: 'fractional-kelly', fullKelly: .12, fraction: .25, fractionalKelly: .03, suggestedRiskPerTrade: .02, maxRiskCap: .02, capped: true } }

export const executionFixture: AnalyticsExecution = { source: edgeFixture.source, calculationVersion: 'v1', audit: { totalTrades: 80, eligibleExecutionTrades: 80, excludedNoInitialRisk: 0, protectionTelemetryTrades: 80, costModelSource: 'configured', marketDataCoverageTrades: 80 }, execution: { trades: [{ tradeId: 't1', realizedR: 1, mfeR: 2, mfePercentile: 70, captureRatio: .5 }], averageMfePercentile: 70, averageCaptureRatio: .5, grossExpectancyR: .2, netExpectancyR: .15, netWinRate: 50, edgeAfterCosts: true, averageCostR: .05, costModel: { tickValueCents: 500, spreadTicks: .25, slippageTicks: .25, feesIncluded: true }, mfeHistogram: [{ fromInclusiveR: 0, toExclusiveR: 1, count: 1 }], exitReasonBreakdown: { manual: 1, stopLoss: 0, takeProfit: 0 } }, decision: { trades: [{ tradeId: 't1', classification: 'goodWin', adherenceScore: 100, tamperedStop: false, tamperedTarget: false }], matrix: { goodWin: 1, goodLoss: 1, badWin: 0, badLoss: 0 }, planAdherenceScore: 95, ruleFollowingDividendR: .1, ruleFollowingDividendCents: 500, breakevenTrades: 0 }, psychology: { tiltScore: 10, slTamperingScore: 5, sizingConsistency: 90, antiStreakScore: 92, postLossSizeEscalations: 0, rapidReentriesAfterLoss: 0, profile: 'composed' } }

const audit = { noInitialStop: 0, invalidRisk: 0, missingMarketData: 0 }
const curve = [{ tradeIndex: 1, tradeId: 't1', closedAt: '2025-03-01T12:00:00Z', cumulativeR: 1, balance: 101_000 }]
export const stopLossFixture: StopLossSimulation = { source: { id: identity.id, type: identity.type, tradeCount: 2 }, includedTrades: 2, excludedTrades: audit, scenarios: [{ reductionPercent: 0, winRate: 50, stoppedOutTrades: 1, averageWinR: 2, expectancyR: .5, totalR: 1, profit: 1_000, profitFactor: 2, averageDrawdownR: -1, equityCurve: curve }, { reductionPercent: 10, winRate: 50, stoppedOutTrades: 1, averageWinR: 2.2, expectancyR: .6, totalR: 1.2, profit: 1_200, profitFactor: 2.2, averageDrawdownR: -.9, equityCurve: curve }], bestScenario: { reductionPercent: 10, criterion: 'profitFactor' }, metadata: { intrabarPolicy: 'conservative' } }
export const rrFixture: RrSimulation = { source: stopLossFixture.source, includedTrades: 2, excludedTrades: audit, scenarios: [{ id: 'current', targetR: null, label: 'Current RR', winRate: 50, profit: 1_000, profitFactor: 2, averageDrawdownPercent: 1, equityCurve: curve }, { id: 'target-1', targetR: 1, label: '1.0R', winRate: 60, profit: 1_200, profitFactor: 2.2, averageDrawdownPercent: .8, equityCurve: curve }], bestScenario: { id: 'target-1', criterion: 'profitFactor' }, metadata: { intrabarPolicy: 'conservative' } }
export const monteFixture: MonteCarloSimulation = { seed: 42, paths: [{ simulationIndex: 1, balances: [100_000, 101_000] }], summary: { averageEndingBalance: 101_000, maxEndingBalance: 101_000, minEndingBalance: 101_000, averageProfitFactor: 2, maxConsecutiveWins: 1, maxConsecutiveLosses: 0, totalWins: 1, totalLosses: 0 }, inputs: { simulationCount: 1, tradesPerSimulation: 1, startBalance: 100_000, averageGain: 1_000, averageLoss: 500, winRatePercent: 50 } }
