import { AlertCircle, ChevronUp, CircleHelp, Plus, RotateCcw, Sparkles } from 'lucide-react'
import { useCallback, useEffect, useId, useState, type FormEvent, type ReactNode } from 'react'
import {
  runMonteCarloSimulation, runRrSimulation, runStopLossSimulation,
  type AnalyticsDrawdown, type AnalyticsPerformance, type AnalyticsSourceType, type MonteCarloSimulation,
  type RrSimulation, type StopLossSimulation,
} from '../../api/analytics'
import { DrawdownChart, HistogramChart, MonteCarloChart, MultiSeriesChart, type DrawdownPoint, type SimulationSeries } from './AdvancedAnalyticsCharts'
import type { ResourceState } from './use-analytics-resource'

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 })
const integer = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
const colors = ['#2962ff', '#7367e8', '#d49b22', '#d9584f', '#55b990', '#76a5f5', '#c56a24', '#7b16eb', '#6fae22', '#ffa53d', '#4d91e5', '#56b84c', '#60dfcb']

function Info({ label, children }: { label: string; children: ReactNode }) {
  const id = useId()
  return <span className="group relative inline-flex"><button type="button" aria-label={`About ${label}`} aria-describedby={id} className="ml-1 inline-grid size-5 place-items-center rounded-md text-[#858b94] hover:bg-[#272a2f] hover:text-white"><CircleHelp size={12} /></button><span id={id} role="tooltip" className="pointer-events-none absolute left-1/2 top-7 z-40 hidden w-72 -translate-x-1/2 rounded-md border border-[#515761] bg-[#0b0d10] p-3 text-left text-xs font-normal leading-5 text-[#c8cdd4] shadow-xl group-hover:block group-focus-within:block">{children}</span></span>
}
function Title({ children, info, action }: { children: ReactNode; info?: string; action?: ReactNode }) { return <div className="mb-4 flex min-h-11 flex-wrap items-center justify-between gap-3"><h2 className="text-[21px] font-semibold tracking-[-0.02em] text-[#f3f5f7]">{children}{info ? <Info label={String(children)}>{info}</Info> : null}</h2>{action}</div> }
function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-[14px] border border-[#3c4148] bg-[#121416] ${className}`}>{children}</section> }
function Stat({ label, value }: { label: string; value: string }) { return <div title={`${label}: ${value}`} tabIndex={0} className="min-h-24 border-l-[3px] border-[#ff6b4a] bg-[#121416] px-4 py-4 outline-none hover:bg-[#17191c]"><p className="text-[13px] text-[#aeb5bf]">{label}</p><p className="mt-1 font-mono text-[21px] font-semibold text-[#f4f6f8] tabular-nums">{value}</p></div> }
function totalExcluded(value: { noInitialStop: number; invalidRisk: number; missingMarketData: number }): number { return value.noInitialStop + value.invalidRisk + value.missingMarketData }
function ErrorNote({ message }: { message: string }) { return <div role="alert" className="my-4 flex items-center gap-2 rounded-lg border border-loss/40 bg-loss/10 px-3 py-2 text-xs text-loss-bright"><AlertCircle size={14} />{message}</div> }
function LoadingNote() { return <div className="my-4 rounded-lg border border-[#343940] px-3 py-2 text-xs text-[#9299a3]">Calculating from completed trades…</div> }

function useSimulation<T>(load: (signal: AbortSignal) => Promise<T>): ResourceState<T> {
  const [state, setState] = useState<ResourceState<T>>({ status: 'loading' })
  useEffect(() => {
    const controller = new AbortController(); setState({ status: 'loading' })
    void load(controller.signal).then((data) => { if (!controller.signal.aborted) setState({ status: 'success', data }) }, (reason: unknown) => { if (!controller.signal.aborted) setState({ status: 'error', error: reason instanceof Error ? reason : new Error('Simulation failed') }) })
    return () => controller.abort()
  }, [load])
  return state
}

export function DrawdownTab({ report }: { report: AnalyticsDrawdown }) {
  const [mode, setMode] = useState<'dollar' | 'percent'>('dollar')
  const points: DrawdownPoint[] = report.equityDrawdown.points.map((point) => ({ date: point.closedAt ? new Date(point.closedAt).toLocaleString() : 'Opening balance', equity: point.equity, peak: point.peakEquity, dollars: point.drawdownAmount, percent: point.drawdownPercent }))
  const mae = report.maximumAdverseExcursion
  return <div className="space-y-11"><section><Title info="Drawdown measures how far equity falls below its previous peak." action={<div className="flex rounded-lg border border-[#3e434a] bg-[#0a0b0d] p-0.5"><button type="button" aria-pressed={mode === 'dollar'} onClick={() => setMode('dollar')} className="min-h-8 rounded-md px-3 font-mono text-xs aria-pressed:bg-[#292d33] aria-pressed:text-white">$</button><button type="button" aria-pressed={mode === 'percent'} onClick={() => setMode('percent')} className="min-h-8 rounded-md px-3 font-mono text-xs aria-pressed:bg-[#292d33] aria-pressed:text-white">%</button></div>}>Drawdown on equity</Title><Panel className="overflow-x-auto px-3 pb-2 pt-3 sm:px-5"><DrawdownChart points={points} mode={mode} /></Panel><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Max drawdown" value={mode === 'dollar' ? money.format(report.equityDrawdown.maxDrawdownAmount) : `${report.equityDrawdown.maxDrawdownPercent.toFixed(2)}%`} /><Stat label="AVG drawdown on equity" value={mode === 'dollar' ? money.format(report.equityDrawdown.averageDrawdownAmount) : `${report.equityDrawdown.averageDrawdownPercent.toFixed(2)}%`} /><Stat label="Time to recovery (days)" value={report.equityDrawdown.averageRecoveryDays.toFixed(1)} /><Stat label="Drawdown frequency" value={String(report.equityDrawdown.drawdownFrequency)} /></div></section><section><Title info="Maximum Adverse Excursion is the greatest unrealized loss before a trade closed, expressed in R.">Maximum adverse excursion</Title><Panel className="overflow-x-auto px-3 py-3 sm:px-5"><HistogramChart bins={mae.histogram.map((bin) => ({ label: bin.label, value: bin.count }))} /></Panel><h3 className="mb-4 mt-8 text-[17px] font-semibold text-[#f1f3f5]">Drawdown on winning trades</h3><div className="grid gap-3 sm:grid-cols-3"><Stat label="AVG drawdown RR" value={`${mae.winningTrades.averageMaeR.toFixed(2)}R`} /><Stat label="Min drawdown RR" value={`${mae.winningTrades.minMaeR.toFixed(2)}R`} /><Stat label="Max drawdown RR" value={`${mae.winningTrades.maxMaeR.toFixed(2)}R`} /></div>{mae.winningTrades.excludedNoInitialRisk + mae.winningTrades.missingMarketDataTrades > 0 ? <ErrorNote message={`${mae.winningTrades.excludedNoInitialRisk} trades without initial risk and ${mae.winningTrades.missingMarketDataTrades} without market data were excluded.`} /> : null}</section></div>
}

function Chip({ active, color, label, onClick }: { active: boolean; color: string; label: string; onClick: () => void }) { return <button type="button" aria-pressed={active} onClick={onClick} style={{ borderColor: color }} className="min-h-8 rounded-full border bg-[#111318] px-3 font-mono text-[11px] text-[#dce0e5] hover:bg-[#1d2025] aria-pressed:bg-[#252a32]">{label}</button> }
function Table({ headers, children, caption }: { headers: string[]; children: ReactNode; caption: string }) { return <div className="overflow-x-auto rounded-[14px] border border-[#3d4249]"><table className="w-full min-w-[850px] border-collapse text-left text-[13px]"><caption className="sr-only">{caption}</caption><thead className="bg-[#090a0c] text-[#eef1f4]"><tr>{headers.map((header) => <th key={header} className="h-14 border-b border-[#3d4249] px-4 text-center font-semibold">{header}</th>)}</tr></thead><tbody className="font-mono text-[#b8bec7]">{children}</tbody></table></div> }

function StopLossSimulator({ source }: { source: { id: string; type: AnalyticsSourceType } }) {
  const [reductions, setReductions] = useState([0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])
  const [selected, setSelected] = useState(10); const [custom, setCustom] = useState('65'); const [showAdd, setShowAdd] = useState(false)
  const load = useCallback((signal: AbortSignal) => runStopLossSimulation(source.type, source.id, reductions, signal), [reductions, source.id, source.type])
  const state = useSimulation(load)
  const add = (event: FormEvent) => { event.preventDefault(); const value = Math.round(Number(custom)); if (value > 0 && value < 100 && !reductions.includes(value)) { setReductions((current) => [...current, value].sort((a, b) => a - b)); setSelected(value); setShowAdd(false) } }
  return <section><Title info="Replays eligible completed trades with tighter initial-stop scenarios.">Stop loss simulator</Title><Panel className="p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex flex-wrap gap-2">{reductions.map((value, index) => <Chip key={value} active={selected === value} color={colors[index % colors.length] ?? '#2962ff'} label={value === 0 ? '0% · Current SL' : `${value}%`} onClick={() => setSelected(value)} />)}</div><button type="button" onClick={() => setShowAdd((value) => !value)} className="flex min-h-10 items-center gap-2 rounded-full bg-active px-5 text-sm text-white"><Plus size={16} />Add scenario</button></div>{showAdd ? <form onSubmit={add} className="mt-4 flex max-w-sm items-end gap-2"><label className="flex-1 text-xs text-[#aeb5bf]">Stop-loss reduction<input type="number" aria-label="Custom stop-loss reduction" value={custom} onChange={(event) => setCustom(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#464b53] bg-[#090a0c] px-3 font-mono text-white" /></label><button className="h-10 rounded-lg bg-active px-4 text-sm text-white">Add</button></form> : null}{state.status === 'loading' || state.status === 'idle' ? <LoadingNote /> : null}{state.status === 'error' ? <ErrorNote message={state.error.message} /> : null}{state.status === 'success' ? <StopLossResults report={state.data} selected={selected} /> : null}</Panel></section>
}
function StopLossResults({ report, selected }: { report: StopLossSimulation; selected: number }) {
  const series: SimulationSeries[] = report.scenarios.map((row, index) => ({ id: String(row.reductionPercent), label: `${row.reductionPercent}% reduction`, color: colors[index % colors.length] ?? '#2962ff', values: row.equityCurve.map((point) => point.cumulativeR) }))
  const excluded = totalExcluded(report.excludedTrades)
  return <><div className="mt-6 overflow-x-auto"><MultiSeriesChart series={series} selectedId={String(selected)} yLabel="Cumulative R" valueFormatter={(value) => `${value.toFixed(1)}R`} ariaLabel="Stop loss simulation equity curves" tooltipRows={(item) => { const row = report.scenarios.find((candidate) => String(candidate.reductionPercent) === item.id); return row ? [{ label: 'Win rate', value: `${row.winRate.toFixed(2)}%` }, { label: 'Stopped out', value: `${row.stoppedOutTrades} of ${report.includedTrades}` }, { label: 'Expectancy', value: `${row.expectancyR.toFixed(2)}R` }, { label: 'Profit', value: money.format(row.profit), tone: row.profit >= 0 ? 'profit' : 'loss' }] : [] }} /></div><div className="mt-3 flex flex-wrap justify-between gap-3"><h3 className="text-xl font-semibold text-white">Results</h3><p className="text-[13px] text-[#b7bdc6]">Best server result: <strong className="text-active-bright">{report.bestScenario.reductionPercent}% reduction</strong>.</p></div>{excluded > 0 ? <ErrorNote message={`${excluded} trades excluded: ${report.excludedTrades.noInitialStop} no stop, ${report.excludedTrades.invalidRisk} invalid risk, ${report.excludedTrades.missingMarketData} missing market data.`} /> : null}<Table headers={['SL reduction', 'Win rate', 'Total R', 'Profit', 'Profit factor', 'Avg drawdown']} caption="Stop loss simulation results">{report.scenarios.map((row, index) => <tr key={row.reductionPercent} className="border-b border-[#34383e]"><th className="h-11 px-4 text-center text-white"><span style={{ color: colors[index % colors.length] }}>●</span> {row.reductionPercent}%</th><td className="px-4 text-center">{row.winRate.toFixed(2)}%</td><td className="px-4 text-center">{row.totalR.toFixed(2)}R</td><td className="px-4 text-center">{money.format(row.profit)}</td><td className="px-4 text-center">{row.profitFactor?.toFixed(2) ?? '—'}</td><td className="px-4 text-center">{row.averageDrawdownR.toFixed(2)}R</td></tr>)}</Table></>
}

function RrSimulator({ source }: { source: { id: string; type: AnalyticsSourceType } }) {
  const [targets, setTargets] = useState([1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]); const [selected, setSelected] = useState('target-1'); const [custom, setCustom] = useState('5.5'); const [showAdd, setShowAdd] = useState(false)
  const load = useCallback((signal: AbortSignal) => runRrSimulation(source.type, source.id, targets, signal), [source.id, source.type, targets])
  const state = useSimulation(load)
  const add = (event: FormEvent) => { event.preventDefault(); const value = Math.round(Number(custom) * 10) / 10; if (value >= .5 && value <= 20 && !targets.includes(value)) { setTargets((current) => [...current, value]); setShowAdd(false) } }
  return <section><Title info="Replays eligible trades against fixed risk-reward targets while preserving their original stop.">RR simulator</Title><Panel className="p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex flex-wrap gap-2">{state.status === 'success' ? state.data.scenarios.map((row, index) => <Chip key={row.id} active={selected === row.id} color={colors[index % colors.length] ?? '#2962ff'} label={row.label} onClick={() => setSelected(row.id)} />) : targets.map((value, index) => <Chip key={value} active={false} color={colors[index % colors.length] ?? '#2962ff'} label={`${value}R`} onClick={() => undefined} />)}</div><button type="button" onClick={() => setShowAdd((value) => !value)} className="flex min-h-10 items-center gap-2 rounded-full bg-active px-5 text-sm text-white"><Plus size={16} />Add target</button></div>{showAdd ? <form onSubmit={add} className="mt-4 flex max-w-sm items-end gap-2"><label className="flex-1 text-xs text-[#aeb5bf]">Risk-reward target<input type="number" step="0.1" aria-label="Custom risk-reward target" value={custom} onChange={(event) => setCustom(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#464b53] bg-[#090a0c] px-3 font-mono text-white" /></label><button className="h-10 rounded-lg bg-active px-4 text-sm text-white">Add</button></form> : null}{state.status === 'loading' || state.status === 'idle' ? <LoadingNote /> : null}{state.status === 'error' ? <ErrorNote message={state.error.message} /> : null}{state.status === 'success' ? <RrResults report={state.data} selected={selected} /> : null}</Panel></section>
}
function RrResults({ report, selected }: { report: RrSimulation; selected: string }) {
  const series: SimulationSeries[] = report.scenarios.map((row, index) => ({ id: row.id, label: row.label, color: colors[index % colors.length] ?? '#2962ff', values: row.equityCurve.map((point) => point.cumulativeR) }))
  const excluded = totalExcluded(report.excludedTrades)
  return <><div className="mt-6 overflow-x-auto"><MultiSeriesChart series={series} selectedId={selected} yLabel="Cumulative R" valueFormatter={(value) => `${value.toFixed(1)}R`} ariaLabel="Risk-reward simulation curves" tooltipRows={(item) => { const row = report.scenarios.find((candidate) => candidate.id === item.id); return row ? [{ label: 'Win rate', value: `${row.winRate.toFixed(2)}%` }, { label: 'Profit', value: money.format(row.profit), tone: row.profit >= 0 ? 'profit' : 'loss' }, { label: 'Profit factor', value: row.profitFactor?.toFixed(2) ?? '—' }] : [] }} /></div><div className="mt-3 flex flex-wrap justify-between gap-3"><h3 className="text-xl font-semibold text-white">Results</h3><p className="text-[13px] text-[#b7bdc6]">Best server result: <strong className="text-active-bright">{report.scenarios.find((row) => row.id === report.bestScenario.id)?.label ?? report.bestScenario.id}</strong>.</p></div>{excluded > 0 ? <ErrorNote message={`${excluded} trades were excluded from this simulation.`} /> : null}<Table headers={['Model', 'Win rate', 'Profit', 'Profit factor', 'Avg drawdown']} caption="Risk-reward simulation results">{report.scenarios.map((row, index) => <tr key={row.id} className="border-b border-[#34383e]"><th className="h-11 px-4 text-center text-white"><span style={{ color: colors[index % colors.length] }}>●</span> {row.label}</th><td className="px-4 text-center">{row.winRate.toFixed(2)}%</td><td className="px-4 text-center">{money.format(row.profit)}</td><td className="px-4 text-center">{row.profitFactor?.toFixed(2) ?? '—'}</td><td className="px-4 text-center">{row.averageDrawdownPercent.toFixed(2)}%</td></tr>)}</Table></>
}

interface MonteInputs { simulations: number; trades: number; startBalance: number; averageGain: number; averageLoss: number; winRate: number }
function MonteCarloSimulator({ performance }: { performance: AnalyticsPerformance }) {
  const defaults: MonteInputs = { simulations: 10, trades: 10, startBalance: performance.overview.accountBalance, averageGain: Math.abs(performance.expectancy.averageWin), averageLoss: Math.abs(performance.expectancy.averageLoss), winRate: performance.overview.winRate }
  const [inputs, setInputs] = useState(defaults); const [result, setResult] = useState<MonteCarloSimulation | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const fields: Array<{ key: keyof MonteInputs; label: string; min: number; max: number; step?: number }> = [{ key: 'simulations', label: 'N. simulations', min: 1, max: 50 }, { key: 'trades', label: 'Trades per sim', min: 1, max: 500 }, { key: 'startBalance', label: 'Start balance $', min: 1, max: 10_000_000, step: .01 }, { key: 'averageGain', label: 'Avg gain', min: .01, max: 1_000_000, step: .01 }, { key: 'averageLoss', label: 'Avg loss', min: .01, max: 1_000_000, step: .01 }, { key: 'winRate', label: 'Win rate', min: .01, max: 100, step: .01 }]
  const submit = async (event: FormEvent) => { event.preventDefault(); const invalid = fields.find((field) => inputs[field.key] < field.min || inputs[field.key] > field.max); if (invalid) { setError(`${invalid.label} must be between ${invalid.min} and ${integer.format(invalid.max)}.`); return } setBusy(true); setError(''); try { setResult(await runMonteCarloSimulation({ simulationCount: Math.round(inputs.simulations), tradesPerSimulation: Math.round(inputs.trades), startBalance: inputs.startBalance, averageGain: inputs.averageGain, averageLoss: inputs.averageLoss, winRatePercent: inputs.winRate })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Simulation failed') } finally { setBusy(false) } }
  const stats = result ? [['Average balance', money.format(result.summary.averageEndingBalance)], ['Max balance', money.format(result.summary.maxEndingBalance)], ['Min balance', money.format(result.summary.minEndingBalance)], ['Average profit factor', result.summary.averageProfitFactor?.toFixed(2) ?? '—'], ['Max consecutive wins', String(result.summary.maxConsecutiveWins)], ['Max consecutive losses', String(result.summary.maxConsecutiveLosses)], ['Total wins', String(result.summary.totalWins)], ['Total losses', String(result.summary.totalLosses)]] : []
  const series: SimulationSeries[] = result?.paths.map((path, index) => ({ id: String(path.simulationIndex), label: `Simulation ${path.simulationIndex}`, color: colors[index % colors.length] ?? '#2962ff', values: path.balances })) ?? []
  return <section><Title info="Runs server-side Monte Carlo paths from the selected assumptions.">Monte Carlo simulation</Title><Panel className="p-4 sm:p-6"><form onSubmit={(event) => void submit(event)} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[repeat(6,minmax(100px,1fr))_auto_auto] lg:items-end">{fields.map((field) => <label key={field.key} className="text-[11px] text-[#aeb5bf]">{field.label}<input type="number" aria-label={field.label} min={field.min} max={field.max} step={field.step ?? 1} value={inputs[field.key]} onChange={(event) => setInputs((current) => ({ ...current, [field.key]: Number(event.target.value) }))} className="mt-1 h-10 w-full rounded-lg border border-[#464b53] bg-[#090a0c] px-3 font-mono text-white" /></label>)}<button type="button" onClick={() => { setInputs(defaults); setResult(null); setError('') }} className="flex h-10 items-center justify-center gap-2 rounded-full border border-[#555b64] px-4 text-xs text-[#d8dce2]"><RotateCcw size={14} />Reset</button><button disabled={busy} className="flex h-10 items-center justify-center gap-2 rounded-full bg-active px-5 text-xs text-white disabled:opacity-50"><Sparkles size={14} />{busy ? 'Running…' : 'Start simulation'}</button></form>{error ? <ErrorNote message={error} /> : null}{result ? <><div className="mt-5 overflow-x-auto"><MonteCarloChart series={series} /></div><h3 className="mt-2 text-[17px] font-semibold text-white">Simulation results</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value]) => <div key={label} title={`${label}: ${value}`} className="min-h-24 rounded-xl border border-[#3d4249] bg-[#111315] p-4"><p className="text-xs text-[#b2b8c1]">{label}</p><p className="mt-1 font-mono text-xl font-semibold text-white">{value}</p></div>)}</div></> : <div className="mt-5 rounded-xl border border-dashed border-[#3d4249] px-5 py-12 text-center text-sm text-[#9299a3]">Set the assumptions and start a server simulation.</div>}</Panel></section>
}

export function SimulationTab({ source, performance }: { source: { id: string; type: AnalyticsSourceType }; performance: AnalyticsPerformance }) {
  return <div className="space-y-11"><p className="text-center text-[13px] text-[#aeb5bf]">Simulations use <strong className="text-[#e4e7eb]">{performance.overview.totalTrades} completed trades</strong> from the selected source.</p><StopLossSimulator source={source} /><RrSimulator source={source} /><MonteCarloSimulator performance={performance} /><button type="button" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="mx-auto flex min-h-10 items-center gap-2 rounded-full border border-[#454a51] px-4 text-xs text-[#b8bec7]"><ChevronUp size={15} />Back to analytics tabs</button></div>
}
